### ISSUE TITLE
No bug tracker listed in docs

### ISSUE THREAD

**Issue by cpansprout** [dnmfarrell/Sub-Attributes#4]
See subject.  Hence there are tickets accumulating in this tracker and also in https://rt.cpan.org/Dist/Display.html?Queue=Sub-Attributes.  If you have a preference for where the bug reports should go, please specify it in the documentation.  If you don’t mind handling two queues, please just close this. :-)

**Comment by dnmfarrell** [comment]
Thanks for this, I didn't notice those RT issues at all. I added it to the Makefile.PL and the POD.
