### ISSUE TITLE
Possible bug: "\$value" instead of "$value"

### ISSUE THREAD

**Issue by cpansprout** [dnmfarrell/Sub-Attributes#5]
On line 93 of Attributes.pm, in version 0.02, you have

```
my $fq_sub = "$class:\:\$value";
```

which has an extra backslash, so $value does not get interpolated.  The tests pass anyway.  Either the tests are not comprehensive enough, or this code path is unnecessary.  I’ll leave it to you to figure out which. :-)

**Comment by dnmfarrell** [comment]
Thank you! This is fixed in `77f4357de66b93ab8c32ca683210f27e60b1a75d`
